openapi: 3.0.3
info:
  title: AuthorizationAPI
  description: |-
    A microservice performing authorization to requested resources
  version: 1.0-SNAPSHOT
servers:
  - description: Authorization API
    url: https://gridhub.com/authorization-api/1.0.0
tags:
  - name: resource
paths:
  /resources/resource:
    get:
      tags:
        - resource
      summary: Get resource
      description: Get acces to resource based on users permissions
      operationId: hasPermissionToAccessResource
      parameters:
        - name: ResourceAccessDTO
          in: query
          description: '{"serviceName":"fooService","endpointPath":"foo/bar/api/serviceName", "role":"fooAdmin", "userSpecificId":"1"}'
          required: true
          schema:
            $ref: '#/components/schemas/ResourceAccessDTO'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpResponse'
        403:
          description: Forbidden - User is not privileged to access the resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpResponse'
        404:
          description: Not Found - Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpResponse'
        500:
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpResponse'
    post:
      tags:
        - resource
      summary: Register resource
      description: Allows admin to create new resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceRegistrationDTO'
      responses:
        201:
          description:  Created - Resource was successfully created
        403:
          description:  Forbidden - User is not privileged ed to access the resource
        405:
          description: Method is not allowed
        500:
          description: Internal error
    delete:
      tags:
        - resource
      summary: Unregister resource
      description: Allows admin to delete specified resource
      parameters:
        - name: ResourceDeregistrationDTO
          in: query
          description: '{"serviceName":"fooService","endpointPath":"foo/bar/api/serviceName", "role":"fooAdmin", "userSpecificId":"1"}'
          required: true
          schema:
            $ref: '#/components/schemas/ResourceDeregistrationDTO'
      responses:
        204:
          description:  Resource deleted successfully
        403:
          description:  Forbidden - User is not privileged to access the resource
        404:
          description:  Not Found - Resource not found
        500:
          description: Internal error

components:
  schemas:
    ResourceAccessDTO:
      type: object
      properties:
        serviceName:
          type: string
        endpointPath:
          type: string
        role:
          $ref: '#/components/schemas/Role'
        userSpecificId:
          type: integer
          format: int64

    ResourceRegistrationDTO:
      type: object
      properties:
        serviceName:
          type: string
        endpointPath:
          type: string
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        userSpecificId:
          type: integer
          format: int64
        role:
          $ref: '#/components/schemas/Role'

    ResourceDeregistrationDTO:
      type: object
      properties:
        serviceName:
          type: string
        endpointPath:
          type: string
        role:
          $ref: '#/components/schemas/Role'
        userSpecificId:
          type: integer
          format: int64

    HttpResponse:
      type: object
      properties:
        statusCode:
          type: integer
          minimum: 100
          maximum: 599
        body:
          type: string
        resourcePath:
          type: string

    Role:
      type: string
      enum:
        - ADMIN
        - USER_SPECIFIC
        - BUYER
        - LOGGED_USER
        - NOT_RESTRICTED